name: Deploy WebAssembly Monero Miner to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v11

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Setup Boost
      run: |
        wget https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz
        tar xzf boost_1_76_0.tar.gz
        cd boost_1_76_0
        ./bootstrap.sh --prefix=/usr/local
        sudo ./b2 install --with-system --with-filesystem --with-thread --with-date_time --with-chrono --with-regex --with-serialization --with-program_options

    - name: Build WebAssembly miner
      run: |
        emcc --version
        ls -R
        make TYPE=release BOOST_ROOT=/usr/local/include LDFLAGS="-L/usr/local/lib"

    - name: List build directory
      run: ls -R build/release

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/release
        publish_branch: gh-pages
        keep_files: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Deploy WebAssembly Monero Miner to GitHub Pages'

    - name: Update README with deployment info
      run: |
        echo -e "\n## Deployment\nThis project is automatically deployed to GitHub Pages on each push to the main branch. You can access the live version at https://${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY#*/}/" >> README.md
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update README with deployment info" || echo "No changes to commit"
        git push
