name: Deploy WebAssembly Monero Miner to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write

env:
  BOOST_VERSION: 1.76.0

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v11

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libboost-all-dev

    - name: Cache Boost
      uses: actions/cache@v3
      with:
        path: /usr/include/boost
        key: ${{ runner.os }}-boost-${{ env.BOOST_VERSION }}

    - name: Debug information
      run: |
        ls -R /usr/include/boost
        echo $BOOST_ROOT
        echo $CXXFLAGS
        echo $LDFLAGS

    - name: Update include paths
      run: |
        sed -i 's#<boost/#</usr/include/boost/#g' src/crypto/hash.h

    - name: Build WebAssembly miner
      run: |
        emcc --version
        ls -R
        make TYPE=release BOOST_ROOT=/usr/include/boost CXXFLAGS="-I/usr/include" LDFLAGS="-L/usr/lib/x86_64-linux-gnu"
      continue-on-error: false

    - name: List build directory
      run: ls -R build/release

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wasm-miner
        path: build/release

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/release
        publish_branch: gh-pages
        keep_files: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Deploy WebAssembly Monero Miner to GitHub Pages'

    - name: Update README
      run: |
        if ! grep -q "## Deployment" README.md; then
          echo -e "\n## Deployment\nThis project is automatically deployed to GitHub Pages on each push to the main branch. You can access the live version at https://${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY#*/}/" >> README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with deployment info"
          git push
        fi
