name: WASM Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Install the Emscripten SDK
    - name: Install Emscripten SDK
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        source ./emsdk_env.sh
        cd ..

    # Build using emmake instead of emcmake (no CMakeLists.txt needed)
    - name: Build with Emscripten (emmake)
      run: |
        source emsdk/emsdk_env.sh
        emmake make

    # Prepare deployment folder
    - name: Prepare deployment folder
      run: |
        mkdir -p deploy
        cp *.js deploy/
        cp *.wasm deploy/
        if [ -f index.html ]; then cp index.html deploy/; fi

    # Upload build artifacts (optional for debugging)
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: deploy
        path: deploy

  deploy:
    needs: build         # Must run after build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    # Checkout the branch for deployment
    - name: Checkout code
      uses: actions/checkout@v3

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
      with:
        folder: deploy
