name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch name if it's different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Emscripten
      uses: mymindstorm/setup-emsdk@v11

    - name: Build project
      run: |
        make TYPE=release
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/release  # Adjust this to your build output directory
        publish_branch: gh-pages  # The branch to deploy to
