name: Deploy WebAssembly Monero Miner to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write

env:
  BOOST_VERSION: 1.76.0
  EMSDK_VERSION: 3.1.71

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v12
      with:
        version: ${{ env.EMSDK_VERSION }}
        actions-cache-folder: 'emsdk-cache'

    - name: Cache Boost for Emscripten
      id: cache-boost
      uses: actions/cache@v3
      with:
        path: ~/boost_emscripten
        key: ${{ runner.os }}-boost-emscripten-${{ env.BOOST_VERSION }}

    - name: Download and Extract Boost for Emscripten
      if: steps.cache-boost.outputs.cache-hit != 'true'
      run: |
        mkdir -p ~/boost_emscripten
        wget https://github.com/emscripten-ports/boost/releases/download/boost-${{ env.BOOST_VERSION }}/boost-${{ env.BOOST_VERSION }}.tar.gz
        tar -xzf boost-${{ env.BOOST_VERSION }}.tar.gz -C ~/boost_emscripten

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Debug information
      run: |
        emcc --version
        ls -R ~/boost_emscripten
        echo "BOOST_ROOT=$HOME/boost_emscripten"
        echo "EMSDK=$EMSDK"

    - name: Build WebAssembly miner
      run: |
        export BOOST_ROOT=$HOME/boost_emscripten
        export CXXFLAGS="-I$BOOST_ROOT/include -I$EMSDK/upstream/emscripten/system/include"
        export LDFLAGS="-L$BOOST_ROOT/lib"
        emcc --clear-cache
        make TYPE=release BOOST_ROOT=$BOOST_ROOT CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS"
      env:
        EMCC_FORCE_STDLIBS: 1

    - name: List build directory
      run: ls -R build/release

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/release
        publish_branch: gh-pages
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Deploy WebAssembly Monero Miner to GitHub Pages'

    - name: Update README
      run: |
        if ! grep -q "## Deployment" README.md; then
          echo -e "\n## Deployment\nThis project is automatically deployed to GitHub Pages on each push to the main branch. You can access the live version at https://${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY#*/}/" >> README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update README with deployment info" && git push)
        fi
